apiVersion: v1
kind: Pod
metadata:
  name: test-forbidden-api
  namespace: demo
spec:
  containers:
  - name: api
    image: nginx:latest # 🌟 Vi phạm: Kéo từ Docker Hub, không phải GHCR chuẩn hạ chữ thường của Ty