apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-store
  namespace: demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          credentials: # 🌟 Điểm mấu chốt: Thêm trường bọc này vào và thụt lề 2 dòng dưới sang phải
            accessKeyIDSecretRef:
              name: aws-creds
              key: access-key
            secretAccessKeySecretRef:
              name: aws-creds
              key: secret-key