apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 5m
    receiver: 'Gmail-Receiver'
    routes:
    # 🌟 BỔ SUNG KHỐI NÀY: Bắt toàn bộ alert bắn ra từ namespace demo
    - matchers:
      - name: namespace
        value: demo
        matchType: =
      receiver: 'Gmail-Receiver'
    # Khối cũ của Ty giữ nguyên
    - matchers:
      - name: severity
        value: critical
        matchType: =
      receiver: 'Gmail-Receiver'
  receivers:
  - name: 'Gmail-Receiver'
    emailConfigs:
    - to: 'dinhvanty206@gmail.com'
      from: 'dinhvanty206@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'dinhvanty206@gmail.com'
      authPassword:
        name: gmail-secret
        key: password