apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    groupBy: ['alertname']
    groupWait: 10s
    groupInterval: 10s
    repeatInterval: 5m                  # Sau 5 phút nếu lỗi chưa hết thì gửi email nhắc lại
    receiver: 'Gmail-Receiver'
    routes:
    - matchers:
      - name: severity
        value: critical                 # Chỉ bắt các alert có nhãn severity: critical để gửi mail
        matchType: =
  receivers:
  - name: 'Gmail-Receiver'
    emailConfigs:
    - to: 'dinhvanty206@gmail.com'        # 🌟 Thay bằng Email nhận của Ty
      from: 'dinhvanty206@gmail.com'      # 🌟 Thay bằng Email gửi (thường trùng email trên)
      smarthost: 'smtp.gmail.com:587'   # Máy chủ SMTP của Google
      authUsername: 'dinhvanty206@gmail.com'
      authPassword:
        name: gmail-secret              # Chúng ta sẽ giấu mật khẩu ứng dụng vào Secret ở bước sau
        key: password