# file: k8s-api/api.yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout            # argoproj.io/v1alpha1
metadata: { name: api, namespace: demo, labels: { app: api } }
spec:
  replicas: 4
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: w9-api:1
        imagePullPolicy: IfNotPresent
        ports: [ { name: http, containerPort: 8080 } ]
        env:
        - { name: ERROR_RATE, value: "0.5" }
        - { name: VERSION,    value: "v2" }
        readinessProbe: { httpGet: { path: /healthz, port: 8080 } }
  strategy:
    canary:   
      steps:
        - setWeight: 25
        # 🌟 TỰ ĐỘNG HÓA: Ép Argo Rollouts chạy phân tích tự động tại bước 25% tải này
        - analysis:
            templates:
              - templateName: flask-api-success-rate # Khớp với tên AnalysisTemplate ở Bước 1
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
#service cho Rollout api, để ServiceMonitor có thể lấy metrics từ endpoint /metrics của con Rollout này               
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: demo
  labels:
    app: api           # 🌟 Khớp với spec.selector.matchLabels của ServiceMonitor!
spec:
  ports:
    - name: http       # 🌟 Khớp với endpoints[0].port của ServiceMonitor!
      port: 8080
      targetPort: 8080
  selector:
    app: api           # Trỏ vào Pod của con Rollout api